import HeadshotAccounting from './headshot-accounting.jpg';
import LinkedInLogo from './linkedin.svg';
import GitHubLogo from './github-logo.svg';
import AWSCertifiedCloudPractitioner from './aws-certified-cloud-practitioner.png';
import CPALogo from './cpa.jpg';
import HTML5Logo from './html5.svg';
import CSS3Logo from './css-logo.svg';
import JSLogo from './js-logo.svg';
import BootstrapLogo from './bootstrap-logo.svg.png';
import ReactLogo from './react-logo.svg';
import PythonLogo from './python_icon.svg';
import JupyterLogo from './Jupyter-logo.png';
import SQLLogo from './Sql_logo.png';
import VBALogo from './vba.png';
import ExcelLogo from './excel-logo.svg';
import AccessLogo from './access-logo.svg';
import WordLogo from './word-logo.svg';
import PeopleSoftLogo from './PeopleSoft.png';
import FIULogo from './fiu-logo.webp';
import MDCLogo from './miami-dade-college.png';
import ForGeeksLogo from './4geeks-logo.webp';
import Liftlog from './lift-log.png';
import PyodideGif from './pyodide.gif';
import TaxRagAppChat from './taxragapp-chat.png';

export const headshotAccounting = HeadshotAccounting;
export const linkedInLogo = LinkedInLogo
export const gitHubLogo = GitHubLogo;
export const awsCertifiedCloudPractitioner = AWSCertifiedCloudPractitioner;
export const cpaLogo = CPALogo;
export const html5Logo = HTML5Logo;
export const css3Logo = CSS3Logo;
export const jsLogo = JSLogo;
export const bootstrapLogo = BootstrapLogo;
export const reactLogo = ReactLogo;
export const pythonLogo = PythonLogo;
export const jupyterLogo = JupyterLogo;
export const sqlLogo = SQLLogo;
export const vbaLogo = VBALogo;
export const excelLogo = ExcelLogo;
export const accessLogo = AccessLogo;
export const wordLogo = WordLogo;
export const peopleSoftLogo = PeopleSoftLogo;
export const fiuLogo = FIULogo;
export const mdcLogo = MDCLogo;
export const forGeeksLogo = ForGeeksLogo;
export const liftlog = Liftlog;
export const pyodideGif = PyodideGif;
export const taxRagAppChat = TaxRagAppChat;